sudo: required
services:
  -docker

before_install:
  - docker build -t tomdevacc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tomdevacc/react-test npm test -- --coverage

after_success:
  - docker build -t tomdevacc/multi-client ./client
  - docker build -t tomdevacc/multi-nginx ./nginx
  - docker build -t tomdevacc/multi-server ./server
  - docker build -t tomdevacc/multi-worker ./worker
# Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tomdevacc/multi-client
  - docker push tomdevacc/multi-nginx
  - docker push tomdevacc/multi-server
  - docker push tomdevacc/multi-worker